version: 1.10.0.{build}
environment:
  TIMEOUT: "60m"

install:
  - choco install -y filezilla.server
  - choco install -y php
  - choco install -y git
  - choco install -y composer -ia '' -overridearguments

build_script:
  - php vendor/bin/behat
