version: 1.10.0.{build}
environment:
  TIMEOUT: "60m"

install:
  - choco install -y filezilla.server
  - choco install -y php
  - choco install -y composer
  - choco install -y git
  - composer install

build_script:
  - php vendor/bin/behat.bat
