sftp:
    image: atmoz/sftp
    volumes:
        - ./volumes/sftp/:/home/gaufrette/share
    command: gaufrette:gaufrette:1001
    ports:
        - "2222:22"
    volumes_from:
        - data
s3:
    image: lphoward/fake-s3
    ports:
       - "4569:4569"
    volumes_from:
        - data
ftp:
    image: helder/vsftpd
    ports:
      - "20-21:20-21"
      - "12020-12025:12020-12025"
    volumes:
      - "./volumes/ftp/:/var/ftp/gaufrette/"
    environment:
      - FTP_VIRT_USER=gaufrette
      - FTP_VIRT_PASS=gaufrette
    volumes_from:
        - data
mongo:
    image: mongo
    ports:
      - 27016:27017
    volumes_from:
        - data
data:
    image: busybox
    volumes:
        - ./volumes/:/data/
    command: ["chmod", "-R", "777", "/data"]
