sftp:
    image: atmoz/sftp
    volumes:
        - ./volumes/sftp/:/home/gaufrette/share
    command: gaufrette:gaufrette:1001
    ports:
        - "2222:22"
    volumes_from:
        - data

s3:
    image: lphoward/fake-s3
    ports:
       - "4569:4569"
    volumes_from:
        - data

ftp:
    image: helder/vsftpd
    ports:
      - "20-21:20-21"
      - "12020-12025:12020-12025"
    volumes:
      - "./volumes/ftp/:/var/ftp/gaufrette/"
    environment:
      - FTP_VIRT_USER=gaufrette
      - FTP_VIRT_PASS=gaufrette
    volumes_from:
        - data

mongo:
    image: mongo
    ports:
      - 27016:27017
    volumes_from:
      - data

mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=gaufrette
      - MYSQL_PASSWORD=gaufrette
      - MYSQL_DATABASE=gaufrette
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

mogilefs_tracker:
  image: rail44/mogile-tracker
  ports:
    - "7001:7001"
  links:
    - mogilefs_db
    - mogilefs_node
  environment:
    - DB_1_PORT_3306_TCP_ADDR=mogilefs_db:3306
    - NODE_1_PORT_7500_TCP_ADDR=mogilefs_node

mogilefs_node:
  image: rail44/mogile-node
  ports:
    - "7500:7500"

mogilefs_db:
  image: orchardup/mysql
#  environment:
#    - MYSQL_ROOT_PASSWORD=''

data:
    build: images/mogilefs
    volumes:
        - ./volumes/:/data/
    command: ["chmod", "-R", "777", "/data"]
