sftp:
    image: atmoz/sftp
    volumes:
        - ./tmp:/home/gaufrette/share
    command: gaufrette:gaufrette:1001
    ports:
        - "2222:22"       
s3:
    image: lphoward/fake-s3
    ports:
       - "4569:4569"
